This is the Junyper Notebook I will be using throughout

In [16]:
import pandas as pd
from miRBench.dataset import get_dataset_df 

print("--- AGO2_CLASH_Hejret2023 Dataset ---")
df1 = get_dataset_df('AGO2_CLASH_Hejret2023', split="test")[['gene', 'noncodingRNA', 'label']]
display(df1.head())

print("\n--- AGO2_eCLIP_Klimentova2022 Dataset ---")
df2 = get_dataset_df('AGO2_eCLIP_Klimentova2022', split="test")[['gene', 'noncodingRNA', 'label']]
display(df2.head())

--- AGO2_CLASH_Hejret2023 Dataset ---
Using cached dataset C:\Users\05vic\.miRBench\datasets\20540907\AGO2_CLASH_Hejret2023\test\dataset.tsv

,gene,noncodingRNA,label
0,GGAGTCTGGAGTCAAACCCAGAGCAGCTGCAGGCCATGAGGCACAT...,AAAGCAAATGTTGGGTGAACGGC,0
1,CAGCTGTGTACAGCGCCATCTCTCTGCCTTCTGTTGCCCCTCACTC...,AATAGCTCAGAATGTCAGTTCTG,0
2,GCCTCATGCGCTCACGGGTTCGGGGGGCCGATGCTGCCCAAGCCAA...,AGAATTCTCTTATCCAACATCAACA,0
3,AAGAAAATGGTTCAAGGGCATGGGGGTTAGAGAATGTTTCTTTTAC...,GCTAAGGAAGTCCTGTGCTCAG,0
4,CCACCTGCAACCCCAATCTCAATCCGGAGGCCAGTAGCACCAGGAT...,TGAAGCGCCTGTGCTCTGCCGAGA,0

--- AGO2_eCLIP_Klimentova2022 Dataset ---
Using cached dataset C:\Users\05vic\.miRBench\datasets\20540907\AGO2_eCLIP_Klimentova2022\test\dataset.tsv

,gene,noncodingRNA,label
0,GCTAACAACATCTGCACAGCACCTTACAGTTTGCAAAGAACGTTCA...,TAAGGTGCATCTAGTGCAGATAG,1
1,TCTTCCTTTTCCCCACGTTCAGTGTAATCTCACTGAACAGTAATAA...,TAAGGTGCATCTAGTGCAGATAG,1
2,ACAGAGCCATATGTACCCTACCCTGCACATTGTTATGCACTTTTCC...,AAAAGTGCTTACAGTGCAGGTAG,1
3,CACTCCATCAGCACTAGCACCTCACTCCATCGGCCCCGGCACCCTG...,TAAGGTGCATCTAGTGCAGATAG,1
4,GTAAGCACTTTATCTCCAGAACTGAGAGCAAAGTTAACAAATCTCA...,TAAAGTGCTTATAGTGCAGGTAG,1

Dataset statistics
- no. of examples
- no. of +ve and -ve
- min, max, mean and med length of gene and noncodingRNA col.
- Alphabet of gene and noncodingRNA col.
- Check for duplicates

In [ ]:
datasets = {"AGO2_CLASH_Hejret2023": df1,
    "AGO2_eCLIP_Klimentova2022": df2}

print('number of examples in each datasets')
for name, df in datasets.items():
    print(f'    Number of examples in {name} dataset: {len(df)}')

print('\nPositive and negative distribution in each dataset:')
for name, df in datasets.items():
    for label in [1,0]:
        print (f'     {name}:Label {label}: {(df['label']==label).sum()}')

print('\nSequence lengths for each dataset:')
for name, df in datasets.items():
    for col in ['gene','noncodingRNA']:
        print (f'\n    Minimum length of {col} in {name} is: {df[col].str.len().min()}')
        print (f'    Maximum length of {col} in {name} is: {df[col].str.len().max()}')
        print (f'    Mean length of {col} in {name} is: {df[col].str.len().mean()}')
        print (f'    Median length of {col} in {name} is: {df[col].str.len().median()}')

print('\nThe alphabet in each dataset is:')
for name, df in datasets.items():
    for col in ['gene', 'noncodingRNA']:
        print(f'{col} in {name} contains: {set("".join(df[col].dropna()))}')

print ('\nThe number of duplicates in each dataset is:')
for name, df in datasets.items():
    ctdf = df['gene'].str.cat(df['noncodingRNA']) #joining gene column with noncodingRNA column per row
    print(f'Number of duplicates in {name} dataset are: {ctdf.duplicated().sum()}')

number of examples in each datasets
    Number of examples in AGO2_CLASH_Hejret2023 dataset: 1018
    Number of examples in AGO2_eCLIP_Klimentova2022 dataset: 954

Positive and negative distribution in each dataset:
     AGO2_CLASH_Hejret2023:Label 1: 495
     AGO2_CLASH_Hejret2023:Label 0: 523
     AGO2_eCLIP_Klimentova2022:Label 1: 477
     AGO2_eCLIP_Klimentova2022:Label 0: 477

Sequence lengths for each dataset:

    Minimum length of gene in AGO2_CLASH_Hejret2023 is: 50
    Maximum length of gene in AGO2_CLASH_Hejret2023 is: 50
    Mean length of gene in AGO2_CLASH_Hejret2023 is: 50.0
    Median length of gene in AGO2_CLASH_Hejret2023 is: 50.0

    Minimum length of noncodingRNA in AGO2_CLASH_Hejret2023 is: 17
    Maximum length of noncodingRNA in AGO2_CLASH_Hejret2023 is: 26
    Mean length of noncodingRNA in AGO2_CLASH_Hejret2023 is: 22.01571709233792
    Median length of noncodingRNA in AGO2_CLASH_Hejret2023 is: 22.0

    Minimum length of gene in AGO2_eCLIP_Klimentova2022 is: 50
    Maximum length of gene in AGO2_eCLIP_Klimentova2022 is: 50
    Mean length of gene in AGO2_eCLIP_Klimentova2022 is: 50.0
    Median length of gene in AGO2_eCLIP_Klimentova2022 is: 50.0

    Minimum length of noncodingRNA in AGO2_eCLIP_Klimentova2022 is: 18
    Maximum length of noncodingRNA in AGO2_eCLIP_Klimentova2022 is: 25
    Mean length of noncodingRNA in AGO2_eCLIP_Klimentova2022 is: 22.333333333333332
    Median length of noncodingRNA in AGO2_eCLIP_Klimentova2022 is: 22.0

The alphabet in each dataset is:
gene in AGO2_CLASH_Hejret2023 contains: {'C', 'T', 'G', 'A'}
noncodingRNA in AGO2_CLASH_Hejret2023 contains: {'C', 'T', 'G', 'A'}
gene in AGO2_eCLIP_Klimentova2022 contains: {'C', 'T', 'G', 'A'}
noncodingRNA in AGO2_eCLIP_Klimentova2022 contains: {'C', 'T', 'G', 'A'}

The number of duplicates in each dataset is:
Number of duplicates in AGO2_CLASH_Hejret2023 dataset are: 0
Number of duplicates in AGO2_eCLIP_Klimentova2022 dataset are: 0

Nucleotide freq per unique miRNA

In [25]:
unique_datasets = {}

for name, df in datasets.items():
    unique_datasets[name] = pd.DataFrame(
        df["noncodingRNA"].unique(),
        columns=["noncodingRNA"],
    )

nucleotides = ["A","G","T","C"]

for name, df in unique_datasets.items():
    for nucleotide in nucleotides:
        df[nucleotide] = df["noncodingRNA"].str.count(nucleotide)

    print (name)
    display (df.head())

AGO2_CLASH_Hejret2023

                noncodingRNA   A  G  T  C
0    AAAGCAAATGTTGGGTGAACGGC   8  8  4  3
1    AATAGCTCAGAATGTCAGTTCTG   7  5  7  4
2  AGAATTCTCTTATCCAACATCAACA  10  1  7  7
3     GCTAAGGAAGTCCTGTGCTCAG   5  7  5  5
4   TGAAGCGCCTGTGCTCTGCCGAGA   4  8  5  7

AGO2_eCLIP_Klimentova2022

              noncodingRNA  A  G  T  C
0  TAAGGTGCATCTAGTGCAGATAG  7  7  6  3
1  AAAAGTGCTTACAGTGCAGGTAG  8  7  5  3
2  TAAAGTGCTTATAGTGCAGGTAG  7  7  7  2
3  CAAAGTGCTTACAGTGCAGGTAG  7  7  5  4
4   ACTGCAGTGAAGGCACTTGTAG  6  7  5  4

K-mer count per unique miRNA

In [29]:
from itertools import product
K_mers = ["".join(combinatoin) for combinatoin in product(nucleotides,repeat=3)]

for name, df in unique_datasets.items():
    for  K_mer in K_mers:
        df[K_mer] = df["noncodingRNA"].str.count(K_mer)

    print (name)
    display (df.head())

AGO2_CLASH_Hejret2023

,noncodingRNA,A,G,T,C,AAA,AAG,AAT,AAC,AGA,...,CGT,CGC,CTA,CTG,CTT,CTC,CCA,CCG,CCT,CCC
0,AAAGCAAATGTTGGGTGAACGGC,8,8,4,3,2,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
1,AATAGCTCAGAATGTCAGTTCTG,7,5,7,4,0,0,2,0,1,...,0,0,0,1,0,1,0,0,0,0
2,AGAATTCTCTTATCCAACATCAACA,10,1,7,7,0,0,1,2,1,...,0,0,0,0,1,1,1,0,0,0
3,GCTAAGGAAGTCCTGTGCTCAG,5,7,5,5,0,2,0,0,0,...,0,0,1,1,0,1,0,0,1,0
4,TGAAGCGCCTGTGCTCTGCCGAGA,4,8,5,7,0,1,0,0,1,...,0,1,0,2,0,1,0,1,1,0

AGO2_eCLIP_Klimentova2022

,noncodingRNA,A,G,T,C,AAA,AAG,AAT,AAC,AGA,...,CGT,CGC,CTA,CTG,CTT,CTC,CCA,CCG,CCT,CCC
0,TAAGGTGCATCTAGTGCAGATAG,7,7,6,3,0,1,0,0,1,...,0,0,1,0,0,0,0,0,0,0
1,AAAAGTGCTTACAGTGCAGGTAG,8,7,5,3,1,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,TAAAGTGCTTATAGTGCAGGTAG,7,7,7,2,1,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,CAAAGTGCTTACAGTGCAGGTAG,7,7,5,4,1,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,ACTGCAGTGAAGGCACTTGTAG,6,7,5,4,0,1,0,0,0,...,0,0,0,1,1,0,0,0,0,0