This is the Junyper Notebook I will be using throughout

In [1]:
from miRBench.dataset import get_dataset_df 

print("--- AGO2_CLASH_Hejret2023 Dataset ---")
df1 = get_dataset_df('AGO2_CLASH_Hejret2023', split="test")[['gene', 'noncodingRNA', 'label']]
display(df1.head())

print("\n--- AGO2_eCLIP_Klimentova2022 Dataset ---")
df2 = get_dataset_df('AGO2_eCLIP_Klimentova2022', split="test")[['gene', 'noncodingRNA', 'label']]
display(df2.head())

--- AGO2_CLASH_Hejret2023 Dataset ---
Using cached dataset C:\Users\05vic\.miRBench\datasets\20540907\AGO2_CLASH_Hejret2023\test\dataset.tsv

,gene,noncodingRNA,label
0,GGAGTCTGGAGTCAAACCCAGAGCAGCTGCAGGCCATGAGGCACAT...,AAAGCAAATGTTGGGTGAACGGC,0
1,CAGCTGTGTACAGCGCCATCTCTCTGCCTTCTGTTGCCCCTCACTC...,AATAGCTCAGAATGTCAGTTCTG,0
2,GCCTCATGCGCTCACGGGTTCGGGGGGCCGATGCTGCCCAAGCCAA...,AGAATTCTCTTATCCAACATCAACA,0
3,AAGAAAATGGTTCAAGGGCATGGGGGTTAGAGAATGTTTCTTTTAC...,GCTAAGGAAGTCCTGTGCTCAG,0
4,CCACCTGCAACCCCAATCTCAATCCGGAGGCCAGTAGCACCAGGAT...,TGAAGCGCCTGTGCTCTGCCGAGA,0

--- AGO2_eCLIP_Klimentova2022 Dataset ---
Using cached dataset C:\Users\05vic\.miRBench\datasets\20540907\AGO2_eCLIP_Klimentova2022\test\dataset.tsv

,gene,noncodingRNA,label
0,GCTAACAACATCTGCACAGCACCTTACAGTTTGCAAAGAACGTTCA...,TAAGGTGCATCTAGTGCAGATAG,1
1,TCTTCCTTTTCCCCACGTTCAGTGTAATCTCACTGAACAGTAATAA...,TAAGGTGCATCTAGTGCAGATAG,1
2,ACAGAGCCATATGTACCCTACCCTGCACATTGTTATGCACTTTTCC...,AAAAGTGCTTACAGTGCAGGTAG,1
3,CACTCCATCAGCACTAGCACCTCACTCCATCGGCCCCGGCACCCTG...,TAAGGTGCATCTAGTGCAGATAG,1
4,GTAAGCACTTTATCTCCAGAACTGAGAGCAAAGTTAACAAATCTCA...,TAAAGTGCTTATAGTGCAGGTAG,1

Dataset statistics
- no. of examples
- no. of +ve and -ve
- min, max, mean and med length of gene and noncodingRNA col.
- Alphabet of gene and noncodingRNA col.
- Check for duplicates

In [24]:
datasets = {"AGO2_CLASH_Hejret2023": df1,
    "AGO2_eCLIP_Klimentova2022": df2}

print('number of examples in each datasets')
for name, df in datasets.items():
    print(f'    Number of examples in {name} dataset: {len(df)}')

print('\nPositive and negative distribution in each dataset:')
for name, df in datasets.items():
    for label in [1,0]:
        print (f'     {name}:Label {label}: {(df['label']==label).sum()}')

print('\nSequence lengths for each dataset:')
for name, df in datasets.items():
    for col in ['gene','noncodingRNA']:
        print (f'\n    Minimum length of {col} in {name} is: {df[col].str.len().min()}')
        print (f'    Maximum length of {col} in {name} is: {df[col].str.len().max()}')
        print (f'    Mean length of {col} in {name} is: {df[col].str.len().mean()}')
        print (f'    Median length of {col} in {name} is: {df[col].str.len().median()}')

print('\nThe alphabet in each dataset is:')
for name, df in datasets.items():
    for col in ['gene', 'noncodingRNA']:
        print(f'{col} in {name} contains: {set("".join(df[col].dropna()))}')

print ('\nThe number of duplicates in each dataset is:')
for name, df in datasets.items():
    ctdf = df['gene'].str.cat(df['noncodingRNA'])
    print(f'Number of duplicates in {name} dataset are: {ctdf.duplicated().sum()}')

number of examples in each datasets
    Number of examples in AGO2_CLASH_Hejret2023 dataset: 1018
    Number of examples in AGO2_eCLIP_Klimentova2022 dataset: 954

Positive and negative distribution in each dataset:
     AGO2_CLASH_Hejret2023:Label 1: 495
     AGO2_CLASH_Hejret2023:Label 0: 523
     AGO2_eCLIP_Klimentova2022:Label 1: 477
     AGO2_eCLIP_Klimentova2022:Label 0: 477

Sequence lengths for each dataset:

    Minimum length of gene in AGO2_CLASH_Hejret2023 is: 50
    Maximum length of gene in AGO2_CLASH_Hejret2023 is: 50
    Mean length of gene in AGO2_CLASH_Hejret2023 is: 50.0
    Median length of gene in AGO2_CLASH_Hejret2023 is: 50.0

    Minimum length of noncodingRNA in AGO2_CLASH_Hejret2023 is: 17
    Maximum length of noncodingRNA in AGO2_CLASH_Hejret2023 is: 26
    Mean length of noncodingRNA in AGO2_CLASH_Hejret2023 is: 22.01571709233792
    Median length of noncodingRNA in AGO2_CLASH_Hejret2023 is: 22.0

    Minimum length of gene in AGO2_eCLIP_Klimentova2022 is: 50
    Maximum length of gene in AGO2_eCLIP_Klimentova2022 is: 50
    Mean length of gene in AGO2_eCLIP_Klimentova2022 is: 50.0
    Median length of gene in AGO2_eCLIP_Klimentova2022 is: 50.0

    Minimum length of noncodingRNA in AGO2_eCLIP_Klimentova2022 is: 18
    Maximum length of noncodingRNA in AGO2_eCLIP_Klimentova2022 is: 25
    Mean length of noncodingRNA in AGO2_eCLIP_Klimentova2022 is: 22.333333333333332
    Median length of noncodingRNA in AGO2_eCLIP_Klimentova2022 is: 22.0

The alphabet in each dataset is:
gene in AGO2_CLASH_Hejret2023 contains: {'A', 'T', 'C', 'G'}
noncodingRNA in AGO2_CLASH_Hejret2023 contains: {'A', 'T', 'C', 'G'}
gene in AGO2_eCLIP_Klimentova2022 contains: {'A', 'T', 'C', 'G'}
noncodingRNA in AGO2_eCLIP_Klimentova2022 contains: {'A', 'T', 'C', 'G'}

The number of duplicates in each dataset is:
Number of duplicates in AGO2_CLASH_Hejret2023 dataset are: 0
Number of duplicates in AGO2_eCLIP_Klimentova2022 dataset are: 0

Nucleotide freq per unique miRNA

In [12]:
unique_miRNA_df1 = pd.DataFrame(df1['noncodingRNA'].unique(), columns=['noncodingRNA'])
unique_miRNA_df2 = pd.DataFrame(df2['noncodingRNA'].unique(), columns=['noncodingRNA'])
unique_miRNA_df1.to_csv('unique_noncodingRNA_Hejret2023.csv', index=False)
unique_miRNA_df2.to_csv('unique_noncodingRNA_Klimentova2022.csv', index=False)
display(unique_miRNA1_df1.head())
display(unique_miRNA2_df2.head())

freq_hejret = {
    'Nucleotide': ['A', 'C', 'G', 'U'],  
    'Frequency': [                      
        unique_miRNA_df1['noncodingRNA'].str.count('A').sum(),
        unique_miRNA_df1['noncodingRNA'].str.count('C').sum(),
        unique_miRNA_df1['noncodingRNA'].str.count('G').sum(),
        unique_miRNA_df1['noncodingRNA'].str.count('U').sum()
    ]
}

freq_klimentova = {
    'Nucleotide': ['A', 'C', 'G', 'U'],  
    'Frequency': [                      
        unique_miRNA_df2['noncodingRNA'].str.count('A').sum(),
        unique_miRNA_df2['noncodingRNA'].str.count('C').sum(),
        unique_miRNA_df2['noncodingRNA'].str.count('G').sum(),
        unique_miRNA_df2['noncodingRNA'].str.count('U').sum()
    ]
}

df1_freq = pd.DataFrame(freq_hejret)
df2_freq = pd.DataFrame(freq_klimentova)
df1_freq.to_csv('Nucleotide freq per unique miRNA_Hejret2023.csv', index=False)
df2_freq.to_csv('Nucleotide freq per unique miRNA_Klimentova2022.csv', index=False)

print("\nNucleotide frequency per unique miRNA: AGO2_CLASH_Hejret2023")
display(df1_freq)

print("\nNucleotide frequency per unique miRNA: AGO2_eCLIP_Klimentova2022")
display(df2_freq)

                noncodingRNA
0    AAAGCAAATGTTGGGTGAACGGC
1    AATAGCTCAGAATGTCAGTTCTG
2  AGAATTCTCTTATCCAACATCAACA
3     GCTAAGGAAGTCCTGTGCTCAG
4   TGAAGCGCCTGTGCTCTGCCGAGA

              noncodingRNA
0  TAAGGTGCATCTAGTGCAGATAG
1  AAAAGTGCTTACAGTGCAGGTAG
2  TAAAGTGCTTATAGTGCAGGTAG
3  CAAAGTGCTTACAGTGCAGGTAG
4   ACTGCAGTGAAGGCACTTGTAG

Nucleotide frequency per unique miRNA: AGO2_CLASH_Hejret2023

  Nucleotide  Frequency
0          A        940
1          C       1064
2          G       1252
3          U          0

Nucleotide frequency per unique miRNA: AGO2_eCLIP_Klimentova2022

  Nucleotide  Frequency
0          A        551
1          C        579
2          G        679
3          U          0

K-mer count per unique miRNA

In [13]:
import itertools

alphabet = ['A', 'C', 'G', 'U']
all_combinations = list(itertools.product(alphabet, repeat=3))
kmer_list = ["".join(item) for item in all_combinations]

combined_data = {
    '3-mer': kmer_list,
    
    'Hejret2023_Count': [
        sum(sum(1 for i in range(len(seq) - 2) if seq[i:i+3] == pattern) 
            for seq in unique_miRNA_df1['noncodingRNA'].dropna())
        for pattern in kmer_list
    ],
    
    'Klimentova2022_Count': [
        sum(sum(1 for i in range(len(seq) - 2) if seq[i:i+3] == pattern) 
            for seq in unique_miRNA_df2['noncodingRNA'].dropna())
        for pattern in kmer_list
    ]
}

df_kmer_summary = pd.DataFrame(combined_data)
df_kmer_summary.to_csv('Kmer_counts_summary.csv', index=False)

print("\n--- Global 3-mer Counts Summary Table ---")
display(df_kmer_summary.head(10)) # Shows the first 10 rows as a preview

--- Global 3-mer Counts Summary Table ---

  3-mer  Hejret2023_Count  Klimentova2022_Count
0   AAA                58                    28
1   AAC                41                    26
2   AAG                55                    30
3   AAU                 0                     0
4   ACA                64                    45
5   ACC                42                    20
6   ACG                21                     7
7   ACU                 0                     0
8   AGA                56                    26
9   AGC                70                    44